name: Publish
on: [ push, pull_request ]

jobs:
  Windows:
    name: Windows
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'
      - name: Publish
        run: dotnet publish Epsilon.Cli --runtime win-x64 --configuration Release -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: Epsilon.Cli - Windows
          path: /home/runner/work/epsilon/epsilon/Epsilon.Cli/bin/Release/net6.0/win-x64/publish/
  
  Linux:
    name: Linux
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'
      - name: Publish
        run: dotnet publish Epsilon.Cli --runtime linux-x64 --configuration Release -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: Epsilon.Cli - Linux
          path: /home/runner/work/epsilon/epsilon/Epsilon.Cli/bin/Release/net6.0/linux-x64/publish